import Head from 'next/head';

export default function Java() {
	return (
		<div className='container'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='page-wrapper'>
				<div className='quote'>
					Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows
					where you live.
				</div>
			</div>
		</div>
	);
}
