import Head from 'next/head';

export default function Contact() {
	return (
		<div className='container'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='page-wrapper'>
				<div className='quote'>Do The Simplest Thing That Could Possibly Work</div>
			</div>
		</div>
	);
}
