import Head from 'next/head';

export async function getStaticProps() {
	return {
		props: {},
	};
}

export default function Contact() {
	return (
		<div className='page-wrapper'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='container'>
				<main>
					<h1 className='quote-title'>Contact Us</h1>
					<div className='quote'>Feel free to reach out to us anytime.</div>
				</main>
			</div>
		</div>
	);
}
