import Head from 'next/head';

export async function getStaticProps() {
	return {
		props: {},
	};
}

export default function Home() {
	return (
		<div className='page-wrapper'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='container'>
				<main>
					<h1 className='quote-title'>Home</h1>
					<div className='quote'>
						I&apos;m not a great programmer; I&apos;m just a good programmer with great habits.
					</div>
				</main>
			</div>
		</div>
	);
}
