import Head from 'next/head';

export default function Python() {
	return (
		<div className='container'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='page-wrapper'>
				<div className='quote'>
					A long descriptive name is better than a short enigmatic name. A long descriptive name is better
					than a long descriptive comment.
				</div>
			</div>
		</div>
	);
}
